# Default values for Mas webapp. https://github.com/SocialGouv/helm-charts/blob/master/webapp/values.yaml
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
---

image:
  repository: registry.gitlab.factory.social.gouv.fr/socialgouv/siret2idcc

deployment:

  port: ${PORT}

  livenessProbe:
    path: /healthz
  readinessProbe:
    path: /healthz

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 2560Mi

  env:
  - name: PORT
    value: "${PORT}"

service:
  port: ${PORT}
  targetPort: ${PORT}

ingress:
  enabled: true
  annotations:
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.class: "azure/application-gateway"
  hosts:
  - host: "siret2idcc.dev.fabrique.social.gouv.fr"
    paths:
      - /
  tls:
  - hosts:
      - "siret2idcc.dev.fabrique.social.gouv.fr"
    secretName: siret2idcc-certificate
...
