#
# Context investigation
#
# - master as prod
# - features branches env
#

include:
  - project: SocialGouv/gitlab-ci-yml
    file: /autodevops_simple_app.yml
    ref: v4.0.1

variables:
  PROJECT: "siret2idcc"
  PORT: 3000
  VALUES_FILE: ./.k8s/values.yml
