---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: siret2idcc-crt
spec:
  secretName: siret2idcc-crt-secret
  dnsNames:
  - siret2idcc.incubateur.social.gouv.fr
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - siret2idcc.incubateur.social.gouv.fr
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
